# Generated by Django 4.2.1 on 2023-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
